// generated by mklib.sh on Mon 23 May 2016 14:17:55 BST
package phplib;

import java.io.*;
import java.math.BigDecimal;
import javax.servlet.*;
import javax.servlet.http.*;

import com.caucho.vfs.*;
import com.caucho.quercus.*;
import com.caucho.quercus.env.*;
import com.caucho.quercus.annotation.*;
import com.caucho.quercus.lib.*;
import com.caucho.quercus.lib.curl.*;
import com.caucho.quercus.lib.date.*;
import com.caucho.quercus.lib.db.*;
import com.caucho.quercus.lib.dom.*;
import com.caucho.quercus.lib.file.*;
import com.caucho.quercus.lib.gettext.*;
import com.caucho.quercus.lib.i18n.*;
import com.caucho.quercus.lib.jms.*;
import com.caucho.quercus.lib.json.*;
import com.caucho.quercus.lib.mail.*;
import com.caucho.quercus.lib.mcrypt.*;
import com.caucho.quercus.lib.reflection.*;
import com.caucho.quercus.lib.regexp.*;
import com.caucho.quercus.lib.session.*;
import com.caucho.quercus.lib.simplexml.*;
import com.caucho.quercus.lib.spl.*;
import com.caucho.quercus.lib.string.*;
import com.caucho.quercus.lib.xml.*;
import com.caucho.quercus.lib.zip.*;
import com.caucho.quercus.lib.zlib.*;

import com.caucho.quercus.lib.ImageModule.QuercusImage;

public class phplib {

  private final Env quercus_context;
    
  public phplib(Env env) {
    this.quercus_context = env;
  } 

}
